export const FETCH_EVENTS_DATA = 'FETCH_EVENTS_DATA';
export const FETCH_EVENTS_DATA_SUCCESS = 'FETCH_EVENTS_DATA_SUCCESS';
export const FETCH_EVENTS_DATA_ERROR = 'FETCH_EVENTS_DATA_ERROR';
export const SELECT_EVENT = 'SELECT_EVENT';
