export const FETCH_EVENTS_DATA = 'FETCH_EVENTS_DATA';
export const FETCH_EVENTS_DATA_SUCCESS = 'FETCH_EVENTS_DATA_SUCCESS';
export const FETCH_EVENTS_DATA_ERROR = 'FETCH_EVENTS_DATA_ERROR';

export const FETCH_EVENTS_BEST_DATA = 'FETCH_EVENTS_BEST_DATA';
export const FETCH_EVENTS_BEST_DATA_SUCCESS = 'FETCH_EVENTS_BEST_DATA_SUCCESS';
export const FETCH_EVENTS_BEST_DATA_ERROR = 'FETCH_EVENTS_BEST_DATA_ERROR';

export const FETCH_VENUE_DATA = 'FETCH_VENUE_DATA';
export const FETCH_VENUE_DATA_SUCCESS = 'FETCH_VENUE_DATA_SUCCESS';
export const FETCH_VENUE_DATA_ERROR = 'FETCH_VENUE_DATA_ERROR';

export const FETCH_FEES_DATA = 'FETCH_FEES_DATA';
export const FETCH_FEES_DATA_ERROR = 'FETCH_FEES_DATA_ERROR';
export const FETCH_FEES_DATA_SUCCESS = 'FETCH_FEES_DATA_SUCCESS';

export const FETCH_CATEGORY_DATA = 'FETCH_CATEGORY_DATA';
export const FETCH_CATEGORY_DATA_SUCCESS = 'FETCH_CATEGORY_DATA_SUCCESS';
export const FETCH_CATEGORY_DATA_ERROR = 'FETCH_CATEGORY_DATA_ERROR';

export const SELECT_EVENT = 'SELECT_EVENT';

export const OPEN_TICKET = 'OPEN_TICKET';
